name: Auto Version Bump

on:
  push:
    branches:
      - main
    paths:
      - "**/*.js"
      - "**/*.py"
      - "package.json"  # adjust paths according to your project
  
jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Bump version
        run: |
          # Run your version bumping logic here
          # For example, run a custom shell script or npm package
          bash ./scripts/bump_version.sh  # (If using a script)
      
      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Bump version"
          git push
